language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'