spring:
    aop:
        auto: true
        proxy-target-class: true
#    datasource:
#       url : jdbc:h2:file:target/workflow-test
#       username : sa
#       password :
#       type: com.alibaba.druid.pool.DruidDataSource
#       driver-class-name : org.h2.Driver
    datasource:
       url : jdbc:mysql://localhost:3306/hsweb?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
       username : root
       password : root
       driver-class-name : com.mysql.jdbc.Driver
    cache:
       type: simple

logging:
  level:
      org.flowable: debug
#      org.activiti: debug
mybatis:
  dynamic-datasource: false
  mapper-locations: classpath*:org/hswebframework/web/workflow/**/*Mapper.xml
server:
  port: 8080