jdbc:
    url: jdbc:mysql://localhost/wb
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
# MyBatis
mybatis:
    typeAliasesPackage: org.hsweb.web.bean.po
    mapperLocations: classpath*:org/hsweb/web/dao/impl/mybatis/mapper/**/mysql/*.xml
    configLocation: classpath:mybatis-config.xml
#LOGGING
logging:
    config: classpath:logback.xml
    path: /var/logger/hsweb